apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: devops-toolkit
spec:
  analyzers: []
  collectors:
  - clusterInfo: {}
  - clusterResources: {}
  - logs:
      selector:
      - app=devops-toolkit
      namespace: production
      limits:
        maxAge: 5h
        maxLines: 1000
